### ISSUE TITLE
Document XHProf configuration.

### ISSUE THREAD

**Issue by ccharlton** [lando/docs#102]
Feature request for _XHProf_ support.

**Comment by qzmenko** [comment]
This is works for me.
```
services:
  appserver:
    build_as_root:
      # Install xhprof.
      - pecl install xhprof && echo "extension=xhprof.so" > $PHP_INI_DIR/conf.d/xhprof.ini
```
