### ISSUE TITLE
VPN, provide some examples for using other networks

### ISSUE THREAD

**Issue by hkirsman** [lando/docs#2]
I'm not able to access url that works with VPN. Locally I get connected but when I try the same wget command in container then it does not connect. Do you think it's something we could add to Lando or is it vpn configuration issue?

**Comment by silverham** [comment]
I can confirm as in comment https://github.com/lando/docs/issues/2#issuecomment-628626067 using `compose` key works for the .amazee.io / pygmy reserve proxy (https://github.com/pygmystack/pygmy) network. Example below from Drupal recipe https://docs.lando.dev/drupal/getting-started.html:

Note the `compose`, `overrides` keys and `networks.yml` file.

**[project]/index.php**
```html
<p>Some html text</p>
```

**[project]/.lando.yml**
```yml 
name: my-first-drupal9-app
recipe: drupal9
config:
  webroot: .
compose:
  - lando-config/networks.yml
services:
  appserver:
    webroot: .
    xdebug: false
    # Pymgy / amazeeeio-haproxy intergration so we share same port number.
    # `LAGOON_LOCALDEV_URL` & `LAGOON_LOCALDEV_HTTP_PORT` for proxy viewing.
    # `LAGOON_ROUTE` for proxy status via `pygmy status`
    # @see https://github.com/amazeeio/docker-haproxy/blob/master/haproxy.tmpl
    # @see https://github.com/pygmystack/pygmy/blob/main/service/library/status.go#L131
    overrides:
      environment:
        LAGOON_LOCALDEV_URL: http://lando-test.docker.amazee.io
        LAGOON_LOCALDEV_HTTP_PORT: 80
        LAGOON_ROUTE: http://lando-test.docker.amazee.io
      networks:
        - amazeeio-network
```

**[project]/lando-config/networks.yml**
```yml
networks:
  amazeeio-network:
    external: true
```
