### ISSUE TITLE
Lando recipe for SonarQube

### ISSUE THREAD

**Issue by tormi** [lando/docs#264]
Here's the Lando recipe for [SonarQube](https://docs.sonarsource.com/sonarqube/latest/):

## `.lando.yml`

```yml
name: sonar

proxy:
  sonar:
    - sonar.lndo.site:9000

services:
  db:
    type: postgres
    portforward: true
    overrides:
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: ''
        POSTGRES_DB: database
  # @see: https://github.com/SonarSource/docker-sonarqube/tree/master/10/community
  # @see: https://github.com/SonarSource/docker-sonarqube/blob/master/example-compose-files/sq-with-postgres/docker-compose.yml
  sonar:
    type: lando
    ssl: true
    sslExpose: false
    depends_on:
      - db
    services:
      image: sonarqube:community
      command: "/opt/sonarqube/docker/entrypoint.sh"
      volumes:
        - sonarqube_data:/opt/sonarqube/data
        - sonarqube_extensions:/opt/sonarqube/extensions
        - sonarqube_logs:/opt/sonarqube/logs
      ports:
        - "9000:9000"
    overrides:
      environment:
        # Lando webroot via environment variable.
        LANDO_WEBROOT: /opt/sonarqube/web
        SONAR_JDBC_URL: jdbc:postgresql://db:5432/database
        SONAR_JDBC_USERNAME: postgres
        SONAR_JDBC_PASSWORD: ''

volumes:
  sonarqube_data:
    driver: local
  sonarqube_extensions:
    driver: local
  sonarqube_logs:
    driver: local

# Tested with Lando version.
version: v3.21
```

## `.gitignore`

```sh
# SonarQube volume directories.
sonarqube_data
sonarqube_extensions
sonarqube_logs
```
