### ISSUE TITLE
xDebug not being enabled though 

### ISSUE THREAD

**Issue by NathanHealea** [lando/docs#279]
Configuring xDebug in the `.lando.yml` file is not working. 

When viewing the `admin/reports/status/php`, xdebug does not show up. 

I've been following these walkthrough: https://docs.lando.dev/guides/lando-with-vscode.html

Here is `.lando.yml` file with sensitive information have been replaced with (...).

```yml
name: ...
recipe: pantheon
config:
  framework: drupal8
  site: ...
  id: ...
  xdebug: true

services:
  appserver:
    webroot: web
    xdebug: true
```

Im not sure if the docs are wrong, as this walkthrough was working prior to updates at the beginning my June, 2024.
