### ISSUE TITLE
Lando with VSCode Guide - Advanced Setup would benefit from a small change

### ISSUE THREAD

**Issue by yorkshire-pudding** [lando/docs#286]
In https://docs.lando.dev/guides/lando-with-vscode.html#advanced-setup tooling is given to switch xdebug on and off.  This works but it outputs an error.

```
$lando xdebug-on
/bin/sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
Reloading Apache httpd web server: apache2.
Xdebug On
```

```
$ lando xdebug-off
/bin/sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
Reloading Apache httpd web server: apache2.
Xdebug Off
```

Changing the tooling to this eliminates this error message and works the same way.

```yaml
  xdebug-on:
    service: appserver
    description: Enable Xdebug.
    user: root
    cmd:
      - docker-php-ext-enable xdebug && kill -USR2 $(pgrep -o php-fpm) 2>/dev/null || /etc/init.d/apache2 reload
      - tput setaf 2 && echo "Xdebug On" && tput sgr 0 && echo
  xdebug-off:
    service: appserver
    description: Disable Xdebug.
    user: root
    cmd:
      - rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && kill -USR2 $(pgrep -o php-fpm) 2>/dev/null || /etc/init.d/apache2 reload
      - tput setaf 1 && echo "Xdebug Off" && tput sgr 0 && echo
```

PR to follow
