### ISSUE TITLE
Docs: Example how to install `oci8` php extension

### ISSUE THREAD

**Issue by hexblot** [lando/docs#33]
This example of build steps can help developers to install Oracle OCI8 extension easily, now that Oracle allows direct download. These extensions are required when PHP application needs a connection to Oracle databases.

This is similar to the SQL Server threads:
https://github.com/lando/lando/issues/1796
https://github.com/lando/lando/pull/1795

Mostly following the items in the [official Oracle documentation](https://www.oracle.com/database/technologies/instant-client/linux-x86-64-downloads.html#ic_x64_inst)

This has been tested with rrc3 and default php7.2 via apache2.4 .

````yaml
services:
  appserver:
    build_as_root:
      - mkdir /opt/oracle
      # Fetch binaries directly from Oracle (!)
      - curl https://download.oracle.com/otn_software/linux/instantclient/19600/instantclient-basic-linux.x64-19.6.0.0.0dbru.zip > /opt/oracle/instantclient-basic.zip
      - curl https://download.oracle.com/otn_software/linux/instantclient/19600/instantclient-sdk-linux.x64-19.6.0.0.0dbru.zip > /opt/oracle/instantclient-sdk.zip
      # Unzip and delete
      - unzip /opt/oracle/instantclient-basic.zip -d /opt/oracle
      - unzip /opt/oracle/instantclient-sdk.zip -d /opt/oracle
      - rm /opt/oracle/instantclient-basic.zip
      - rm /opt/oracle/instantclient-sdk.zip
      # Make OS aware of newly installed libraries
      - echo /opt/oracle/instantclient_19_6 > /etc/ld.so.conf.d/oracle-instantclient.conf
      - ldconfig -v
      # Install and enable OCI8
      - echo "instantclient,/opt/oracle/instantclient_19_6" | pecl install oci8
      - docker-php-ext-enable oci8
````

**Comment by yogeshmpawar** [comment]
Thanks @hexblot ,
Your code really helps us a lot. Faced lots of issues while trying this - https://docs.lando.dev/guides/installing-php-extensions-on-lando.html

Thank you so much.

**Comment by adamfranco** [comment]
In case it helps anyone stumbling upon this thread, this is what worked for me to get Oracle oci8 working on Apple M1/M2 `arm64` with PHP 8.1:

```
config:
  php: 8.1
services:
  appserver:
    build_as_root:
      - mkdir /opt/oracle
      # Fetch binaries directly from Oracle (!)
      - curl https://download.oracle.com/otn_software/linux/instantclient/191000/instantclient-basic-linux.arm64-19.10.0.0.0dbru-2.zip > /opt/oracle/instantclient-basic.zip
      - curl https://download.oracle.com/otn_software/linux/instantclient/191000/instantclient-sdk-linux.arm64-19.10.0.0.0dbru.zip > /opt/oracle/instantclient-sdk.zip
      # Unzip and delete
      - unzip /opt/oracle/instantclient-basic.zip -d /opt/oracle
      - unzip /opt/oracle/instantclient-sdk.zip -d /opt/oracle
      - rm /opt/oracle/instantclient-basic.zip
      - rm /opt/oracle/instantclient-sdk.zip
      # Make OS aware of newly installed libraries
      - echo /opt/oracle/instantclient_19_10 > /etc/ld.so.conf.d/oracle-instantclient.conf
      - ldconfig -v
      # Install libaio1 -- when missing was preventing the extension from loading.
      - apt update
      - apt install libaio1
      # Install and enable OCI8
      - echo "instantclient,/opt/oracle/instantclient_19_10" | pecl install oci8-3.2.1
      - docker-php-ext-enable oci8
```

A few notes:

- The instant client urls have changed since the original post, I was able to find them at: https://www.oracle.com/database/technologies/instant-client/linux-arm-aarch64-downloads.html
- The latest oci8 PECL package (3.3.0) only works with PHP 8.2, so to get it working on PHP 8.1 I needed to specify an older version [as described here](https://pecl.php.net/package/oci8/3.2.0). If you are using PHP 8.2 the second to last line can just use `pecl install oci8`
- I also had to install `libaio1` to get the extension to load. I was getting warnings like the following without it: `Warning: PHP Startup: Unable to load dynamic library 'oci8' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20210902/oci8 (/usr/local/lib/php/extensions/no-debug-non-zts-20210902/oci8: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20210902/oci8.so (libaio.so.1: cannot open shared object file: No such file or directory)) in Unknown on line 0`
