### ISSUE TITLE
Subdomains do not work [SOLVED]

### ISSUE THREAD

**Issue by milkovsky** [lando/docs#54]
Subdomains do not work for me.
I see only `404 page not found` on the page.

OS: Ubuntu 18.04.2 LTS
lando version: v3.0.0-rc.14
docker --version: Docker version 18.09.4, build d14af54266

Test 1:
As suggested in https://docs.devwithlando.io/config/proxy.html#sub-subdomains I have used a hypenated subdomain.
Content of the `lando.yml`:
```
name: mysite
recipe: drupal8

config:
  webroot: docroot

proxy:
  appserver:
    - ch-mysite.lndo.site
```

1. `lando start`.
2. See the both htts and https ch-mysite.lndo.site URLS in red color.
3. Visit https://ch-mysite.lndo.site in browser
4. Accept the certificate
5. See `404 page not found`

Test 2:
Content of the `lando.yml`:
```
name: mysite
recipe: drupal8

config:
  webroot: docroot

proxy:
  appserver:
    - mysite.lndo.site
    - ch.mysite.lndo.site
    - ch-mysite.lndo.site
    - '*.mysite.lndo.site'
```
1. `lando start`.
2. See all the URLs with subdomains hypenated subdomains and in red color.
3. Visit any subdomain page in browser
4. Accept the certificate
5. See `404 page not found`

In addition I have tried to run `lando start -vvv` and I see:
```
info: Checking to see if https://ch.mysite.lndo.site is ready.
info: Checking to see if https://ch-mysite.lndo.site is ready.
verbose: https://ch.mysite.lndo.site not currently accessible
verbose: https://ch-mysite.lndo.site not currently accessible
```

Related issues:
https://github.com/lando/lando/issues/1230
https://github.com/lando/lando/issues/618
https://github.com/lando/lando/issues/157

**Solution:**
Update lando version to v3.0.0-rc.17.
