### ISSUE TITLE
Document how to enable PHP Sockets inside Lando

### ISSUE THREAD

**Issue by greggmarshall** [lando/docs#62]
How would I enable the PHP sockets  extension in Lando.  Mink-zombie-driver is complaining about it not being enabled.  I've tried the
     - apt-get update -y
     - apt-get install sockets -y
     - pecl install sockets
     - docker-php-ext-enable sockets
but apt-get install can't find sockets.  it is possible it has a different name, but I can't find it.

**Describe the change you'd like**
I'd like to see documentation that would tell me how to have a lando environment that would run the Drupal behat mink-zombie-driver which requires sockets.

**Comment by andrewg211** [comment]
```
services:
  appserver:
    build_as_root:
      - apt-get update
      - apt-get install -y autoconf
      - docker-php-ext-install sockets
```
