### ISSUE TITLE
Document how to get IPv6 support rolling in lando

### ISSUE THREAD

**Issue by metalbote** [lando/docs#66]
System: v3.0.0-rc.17 on openSuSE Tumbleweed (5.1.16-1-default)

```yml
name: mysite
env_file:
  - .env
recipe: drupal8
config:
  php: '7.2'
  webroot: web
  via: apache
  database: mariadb
  drush: /app/private/bin/drush
  xdebug: false
  config:
    php: .lando/php.ini
    database: .lando/my.cnf
proxy:
  appserver:
    - mysite.lando
  mail:
    - mail.lando
  pma:
    - pma.lando
services:
  appserver:
    type: php:7.2
    via: apache
    ssl: true
    webroot: web
    xdebug: false
    composer: []
    drush: 8
    config:
      php: .lando/php.ini
    build_as_root:
      - docker-php-ext-install sockets && docker-php-ext-enable sockets
      - apt-get update -y
      - /bin/sh -c 'echo "PATH=\"\$PATH:/app/private/bin\"" >> /etc/environment'
    build:
      - /bin/sh -c 'COMPOSER_MEMORY_LIMIT=-1 composer install'
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=appserver"
  selenium:
    type: compose
    services:
      image: robcherry/docker-chromedriver
      expose:
        - "4444"
      environment:
        CHROMEDRIVER_WHITELISTED_IPS: ""
        CHROMEDRIVER_URL_BASE: "/wd/hub"
      security_opt:
        - seccomp:unconfined
      command: ["/usr/local/bin/supervisord", "-c", "/etc/supervisord.conf"]
  database:
    type: mariadb
    portforward: false
    config:
      database: .lando/my.cnf
  mail:
    type: mailhog:v1.0.0
    portforward: false
    hogfrom:
      - appserver
  pma:
    type: phpmyadmin
    hosts:
      - database
tooling:
  behat:
    service: appserver
    description: "Run behat stuff"
    cmd: /app/private/bin/behat
  composer:
    service: appserver
    description: Run composer commands
    cmd: /usr/local/bin/composer --ansi
  drupal:
    service: appserver
    description: Run drupal commands
    cmd: /app/private/bin/drupal --root=/app/web
  drush:
    service: appserver
    cmd: /app/private/bin/drush --root=/app/web
  phing:
    service: appserver
    cmd: /app/private/bin/phing
  php:
    service: appserver
  phpcs:
    service: appserver
    cmd: /app/private/bin/phpcs
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"
    cmd: /app/private/bin/phpunit
  mysql:
    service: database
    cmd: mysql -uroot
  robo:
    service: appserver
    cmd: /app/private/bin/robo
```
Our git server is running on an ipv6 only server, and i run composer install with vcs repositories enabled to retrieve current code.

On our development machines this works totally fine, as git clone etc. do their job. Spinning up lando stucks at composer install when trying to clone from ipv6 server.

As ipv6 is a problem for docker itself... it took me hours to solve this for other containers on our dev workstations, lando does not behave like every other container.
(HINT: If someone needs ipv6 for docker, [this](https://github.com/robbertkl/docker-ipv6nat) was the best way to go so far on non static systems)

So, every container running on the system gets an ipv6 address and is able to ping ipv6 server, lando container quits with following error:

`Connecting to gitserver (gitserver)|2a02:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx|:443... failed: Cannot assign requested address.
Retrying.`

Any ideas to solve?
