### ISSUE TITLE
Add documentation on getting more logs to show up in lando logs

### ISSUE THREAD

**Issue by kristoftorfs** [lando/docs#87]
Feature Request
==========

> Please explain your request and its importance in the form of a user story.

Most of the time during development I have a terminal open, following the container logs by running `lando logs -f`. It would be nice if I could include my application logs there as well.

> Please provide some detail on how lando can help solve this problem

Add an option to `.lando.yml` called logging, where the user can define keys (log name) and the location to the log file, after which it will be included it the `lando logs` command. Sample `.lando.yml` below.

```yaml
name: myproject
recipe: lemp
config:
  webroot: public
  database: mysql
services:
  appserver:
    config:
      server: config/nginx.conf
logging:
  symfony: var/logs/dev.log
  import: var/logs/import.log
```
