### ISSUE TITLE
Help setting up database replication

### ISSUE THREAD

**Issue by kostajh** [lando/docs#98]
I work on [MediaWiki](https://www.mediawiki.org), and having database replication in my local development environment is very useful for reproducing production issue.

Here's my `.lando.yml` file:

``` yaml
name: mw-lando
recipe: lamp
config:
  webroot: .
  xdebug: true
  php: 7.2
excludes:
  - vendor
  - node_modules
  - resources
  - tests
  - cache
services:
  redis:
    type: redis
    portforward: true
  appserver:
    build:
      - composer install
  database:
    overrides:
      environment:
        MYSQL_REPLICATION_MODE: master
        MYSQL_REPLICATION_USER: replicator
        MYSQL_REPLICATION_PASSWORD: replicator
        MYSQL_USER: lamp
        MYSQL_DATABASE: lamp
        ALLOW_EMPTY_PASSWORD: yes
    type: mysql:5.7
    portforward: true
  databasereplica:
    type: mysql:5.7
    portforward: true
    environment:
      MYSQL_REPLICATION_MODE: slave
      MYSQL_REPLICATION_USER: replicator
      MYSQL_REPLICATION_PASSWORD: replicator
      MYSQL_DATABASE: lamp
      MYSQL_MASTER_HOST: database
      ALLOW_EMPTY_PASSWORD: yes
tooling:
  mysql:
    service: masterdb
    cmd: mysql -uroot
```

A couple of notes/observations:

- I followed the env variables from https://github.com/bitnami/bitnami-docker-mysql/blob/master/docker-compose-replication.yml
- ALLOW_EMPTY_PASSWORD doesn't seem to work, since if I remove MYSQL_REPLICATION_PASSWORD then I see access is denied for the `replicator` user

Replication isn't happening. Maybe I need custom .cnf files? Although the Bitnami docker-compose file says using these variables should just work...
